# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [3]:
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [4]:
print("numpy version", np.__version__)


numpy version 2.3.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [10]:
from numpy import random
#print("uniform [0,1]", rng.random(5))
#random.randrange(20, 50, 3))
a = np.random.rand(2, 3, 5) 





### 4. Print a.


In [11]:
print(f"a = {a}")


a = [[[0.53330354 0.66584445 0.0670341  0.44035854 0.82280686]
  [0.42871793 0.19050046 0.340061   0.39567267 0.67013627]
  [0.61957796 0.55700979 0.23329651 0.18376604 0.57113349]]

 [[0.35388546 0.82897349 0.7549713  0.96117879 0.95358504]
  [0.13171    0.00594618 0.92098233 0.96838027 0.45239096]
  [0.73406676 0.7382745  0.14510544 0.44234376 0.97916803]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [17]:
b = np.ones([5, 2, 3]) 
print("b =", b)


b = [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [18]:
print("b =", b)


b = [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [20]:
print("a.size=", a.size)
print("b.size=", b.size)


a.size= 30
b.size= 30



### 8. Are you able to add a and b? Why or why not?


In [23]:
# it is not possible because they don't have similar row and column 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [27]:
#b_dim= 5 *2 * 3  -> b_dim= 2*3*5  
#np.transpose(originalArray, (1, 2, 0))
c = np.transpose(b, (1, 2, 0))
print("a.shape =", a.shape)
print("b.shape =", b.shape)
print("c.shape =", c.shape)


a.shape = (2, 3, 5)
b.shape = (5, 2, 3)
c.shape = (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
print ("d = ", d)
#because we have the same number of dimensions for a and c


d =  [[[1.53330354 1.66584445 1.0670341  1.44035854 1.82280686]
  [1.42871793 1.19050046 1.340061   1.39567267 1.67013627]
  [1.61957796 1.55700979 1.23329651 1.18376604 1.57113349]]

 [[1.35388546 1.82897349 1.7549713  1.96117879 1.95358504]
  [1.13171    1.00594618 1.92098233 1.96838027 1.45239096]
  [1.73406676 1.7382745  1.14510544 1.44234376 1.97916803]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [30]:
print ("d = ", d)



d =  [[[1.53330354 1.66584445 1.0670341  1.44035854 1.82280686]
  [1.42871793 1.19050046 1.340061   1.39567267 1.67013627]
  [1.61957796 1.55700979 1.23329651 1.18376604 1.57113349]]

 [[1.35388546 1.82897349 1.7549713  1.96117879 1.95358504]
  [1.13171    1.00594618 1.92098233 1.96838027 1.45239096]
  [1.73406676 1.7382745  1.14510544 1.44234376 1.97916803]]]



### 12. Multiply a and c. Assign the result to e.


In [31]:
e = a * c
print("e =", e)


e = [[[0.53330354 0.66584445 0.0670341  0.44035854 0.82280686]
  [0.42871793 0.19050046 0.340061   0.39567267 0.67013627]
  [0.61957796 0.55700979 0.23329651 0.18376604 0.57113349]]

 [[0.35388546 0.82897349 0.7549713  0.96117879 0.95358504]
  [0.13171    0.00594618 0.92098233 0.96838027 0.45239096]
  [0.73406676 0.7382745  0.14510544 0.44234376 0.97916803]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
# no





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [34]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("d_max =", d_max)
print("d_min =", d_min)
print("d_mean =", d_mean)




d_max = 1.9791680270606058
d_min = 1.0059461782008894
d_mean = 1.5363393974638024



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [40]:
#f = np.zeros(shape=(2, 3, 5))
f = np.empty([2, 3, 5])
print("f =", f)


f = [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [52]:
for i in range(0,2):
    for j in range(0,3):
        for k in range(0,5):
            if d[i, j, k] == d_max:
                f[i, j, k] = 100  
            elif d[i, j, k] > d_mean and a[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif (d[i, j, k] > d_min and d[i, j, k] < d_mean):
                f[i, j, k] = 25
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0

print("f =", f)  
print(d)              



f = [[[ 25.  75.  25.  25.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  25.  25.  75.]]

 [[ 25.  75.  75.  75.  75.]
  [ 25.   0.  75.  75.  25.]
  [ 75.  75.  25.  25. 100.]]]
[[[1.53330354 1.66584445 1.0670341  1.44035854 1.82280686]
  [1.42871793 1.19050046 1.340061   1.39567267 1.67013627]
  [1.61957796 1.55700979 1.23329651 1.18376604 1.57113349]]

 [[1.35388546 1.82897349 1.7549713  1.96117879 1.95358504]
  [1.13171    1.00594618 1.92098233 1.96838027 1.45239096]
  [1.73406676 1.7382745  1.14510544 1.44234376 1.97916803]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [53]:
print("f =", f) 


f = [[[ 25.  75.  25.  25.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  25.  25.  75.]]

 [[ 25.  75.  75.  75.  75.]
  [ 25.   0.  75.  75.  25.]
  [ 75.  75.  25.  25. 100.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [67]:
e = np.empty((2,3,5), dtype='object')
for i in range(0,2):
    for j in range(0,3):
        for k in range(0,5):
            if d[i, j, k] == d_max:
                e[i, j, k] = 'E' 
            elif d[i, j, k] > d_mean and a[i, j, k] < d_max:
                e[i, j, k] = 'D'
            elif d[i, j, k] == d_mean:
                e[i, j, k] = 'c'
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                e[i, j, k] = 'B'
            elif d[i, j, k] == d_min:
                e[i, j, k] = 'A'

print("e =", e)  


e = [[['B' 'D' 'B' 'B' 'D']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'B' 'B' 'D']]

 [['B' 'D' 'D' 'D' 'D']
  ['B' 'A' 'D' 'D' 'B']
  ['D' 'D' 'B' 'B' 'E']]]
